### ISSUE TITLE
Endpoints for common date ranges

### ISSUE THREAD

**Issue by pezholio** [theodi/bothan#151]
So, to get metrics for today, you can go to `/metric/today`, and metrics for the last month, you can go to `/metric/last-month`. This should also be configurable in the dashboard view

**Comment by quadrophobiac** [comment]
just saw that these endpoints are already in the code. In terms of this being configurable in the dashboard view I was thinking of a drop down menu that lists the date ranges, with heading Default Date Range. Would it be worthwhile making this configuration available in the metadata edit page as well @pezholio?
