### ISSUE TITLE
Allow title editing when editing dashboard

### ISSUE THREAD

**Issue by Floppy** [theodi/bothan#160]
I made a dashboard, and I can edit it to add more things, change colours, etc, but I can't edit the titles I've given things.

**Comment by Floppy** [comment]
Or are they stored in the metadata for a metric?

**Comment by pezholio** [comment]
Oh, weird. I thought that had been merged in.

**Comment by pezholio** [comment]
Yeah, #156 should've done it :/

**Comment by Floppy** [comment]
I've just edited the metadata and it's worked so that's fine, but it just might be something people expect to be able to do there and then.

**Comment by pezholio** [comment]
OIC - you mean editing the titles once you've created a dashboard? Yeah, I don't think I allowed for that. That should totally be a thing users can do.

**Comment by Floppy** [comment]
It could be as simple as linking to the metadata editing page.

**Comment by pezholio** [comment]
You don't even need to edit the metadata now, titles can be edited on the fly, so it's just a case of exposing them on the edit page
