### ISSUE TITLE
Document with Swagger

### ISSUE THREAD

**Issue by pezholio** [theodi/bothan#173]
We should totally use Swagger to document the API. Maybe using https://github.com/ruby-grape and https://github.com/ruby-grape/grape-swagger. This would also have the added effect of decoupling the API code from the visualisation code.

**Comment by Floppy** [comment]
Can we use swagger without rewriting the API to use Grape? Or is that simple enough anyway? @pezholio any experience would be helpful, otherwise we'll just work it out :)

**Comment by quadrophobiac** [comment]
@pezholio @floppy In terms of what we want documented: would only the API endpoints mentioned in current readme (pertaining exclusively to metrics and their metadata) be documented via Grape or would the Dashboard endpoints also be documented? From naive POV it seems like the Dashboard portion of the Apps strength is being GUI and WYSIWYG

**Comment by Floppy** [comment]
Yeah, dashboard endpoints are definitely a secondary concern, being built for human use.

**Comment by quadrophobiac** [comment]
@Floppy I have a question - where is the auto documented swagger API envisioned as existing? Is it for inclusion in lieu of (and at the same URL as) [bothan.io/api](https://bothan.io/api.html) OR is it envisioned as an additional page that is generated for every users who generate their own Bothan instance via the Heroku sign up?

**Comment by Floppy** [comment]
Hm, good question. it could be either, really. If it's in the app, then it's going to be correctly set up with the right URLs, etc. I'm guessing because swagger and grape are part of the app, then it will be there rather than on bothan.io itself.

**Comment by quadrophobiac** [comment]
cool, good to have clarity. I guess the bothan.io docs URL could then point to https://demo.bothan.io/(whatever-stub-is-decided-for-documentation)
