### ISSUE TITLE
Build some libraries

### ISSUE THREAD

**Issue by pezholio** [theodi/bothan#174]
The API is quite simple, but it'd be nice to have some libraries in a few languages (say Ruby and Node.js) to help drive adoption.

**Comment by pikesley** [comment]
Sounds a bit... socialist

**Comment by pezholio** [comment]
Lulz. I've updated the comment now to add some context 😄

**Comment by quadrophobiac** [comment]
Closing this as the libraries are established - [node](https://github.com/theodi/bothan.js) and [ruby](https://github.com/theodi/bothan.rb)
