### ISSUE TITLE
Responsive Design for Dashboards

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/bothan#198]
adding this feature seems pretty essential the more this is demo'd to people, suspect majority of people leaning to KPI's would like to display them on tablets

**Comment by pezholio** [comment]
I'm pretty sure they are responsive already?

**Comment by quadrophobiac** [comment]
Tried it on my Android FF mobile and it rendered wonky - I'll check it in Chrome and see how it fares

**Comment by quadrophobiac** [comment]
Checked it on Chrome and it was much the same - could be my handset (Oneplus) - can anyone else (@pezholio, @Floppy) check how https://demo.bothan.io/dashboards/bothan renders on mobile in landscape or on a tablet if they own one?

**Comment by quadrophobiac** [comment]
The grid is responsive but the generated iframes containing the visualisations are not

**Comment by quadrophobiac** [comment]
http://blog.apps.npr.org/pym.js/

**Comment by quadrophobiac** [comment]
@pezholio I apologise you were correct - what I was noticing was what happened when orientation shifted from portrait to landscape, or what can be simulated in manually resizing a browser. Under those two events the iframes no longer display the visualisations correctly - because (presumably) plot.ly renders the initial graph proportionately to the initial height and width available to it.
I'm inclined to think both the conditions where I notice this bug are edge cases. 
There are still some cases that would be worth weeding out - like the width threshold below which Bothan should stack the grid rather than attempt a 2 * 2 rendering. I'll create a separate ticket for that as its far more granular than what this one proposed
