### ISSUE TITLE
Include Screencast Documentation for Tutorial 

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/bothan#209]
@pezholio do you have any thoughts on where you'd like these videos to be embedded? Would including them at the top of the tutorial page to which each video corresponds (https://bothan.io/setting-up.html, https://bothan.io/adding-data.html, https://bothan.io/building-a-dashboard.html) be satisfactory

**Comment by pezholio** [comment]
Yeah, that's what I was thinking 👍

**Comment by quadrophobiac** [comment]
cool, TY!

https://vimeo.com/215668663   
https://vimeo.com/215669175   
https://vimeo.com/215669413

**Comment by quadrophobiac** [comment]
completed in PR #210
