### ISSUE TITLE
Enable deletion of an endpoint

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/bothan#252]
Currently users cannot delete an endpoint. I'd see this as a very negative aspect of the User Experience, ability to undo and do-over are helpful comforts when dealing with something new and I think the considerations that open up from what Bothan affords create a user environment where that comfort would be desired.

It'd be good to know if the lack of a delete function is feature or bug? Is there a design principle guiding why this isn't yet part of Bothan @Floppy & @pezholio?

**Comment by Floppy** [comment]
We just never made one. I'd say being able to delete items and entire metrics through some admin UI would be a great additional feature.

**Comment by quadrophobiac** [comment]
I've just been appreciating how Bothan integrates this https://theodi.org/guides/marking-up-your-dataset-with-dcat in the service of machine readability.
I have a broader question related to the purpose of this ticket fuelled entirely by my ignorance of how such standards are intended to function RE posterity - would any problems be created if a data resource marked up with DCAT was then deleted and it's URL 404-ing henceforth? @ldodds & @JeniT cc-ing you in case you know the answer off the top of your heads

**Comment by Floppy** [comment]
Deletion isn't something someone should really do (don't break the web), but if something IS deleted, a 404 is the right thing. Upstream clients should handle that.

**Comment by olivierthereaux** [comment]
410 Gone?

**Comment by Floppy** [comment]
Good point. I always forget that one.

**Comment by olivierthereaux** [comment]
Nice and niche. To be fair I am yet to find any client doing anything useful with it.
