### ISSUE TITLE
Handle oddball edge-cases

### ISSUE THREAD

**Issue by pikesley** [theodi/bothan#32]
Ala http://metrics.theodi.org/metrics/weighted-pipeline/2016-01-03T17:25:46+00:00/2016-02-02T17:25:46+00:00.json

**Comment by pikesley** [comment]
I have no idea where to even start with this 

http://metrics.theodi.org/metrics/2014-q3-completed-tasks/2016-01-04T10:51:47+00:00/2016-02-03T10:51:47+00:00.json

**Comment by Floppy** [comment]
Ill-defined, don't know what to fix. Unless you can remember @pikesley :)
