### ISSUE TITLE
Write installation instructions

### ISSUE THREAD

**Issue by Floppy** [theodi/bothan#64]
Or some sort of setup wizard

**Comment by Floppy** [comment]
Make the process as smooth as possible

**Comment by pezholio** [comment]
Link to Heroku deploy stuff etc is here - http://theodi.github.io/metrics-api/

**Comment by pezholio** [comment]
The Heroku deploy page might be a bit too generic though - could improve this by using the [Heroku Platform API](https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api#creating-an-app-setup), which might give us more control. What we have is probably OK for Alpha though

**Comment by pezholio** [comment]
This is done - might be worth @pikesley trying it tomorrow to test the flow

**Comment by pikesley** [comment]
* `METRICS_API_CERTIFICATE_URL` is a mandatory field, which leads to a bootstrapping problem
* Do I really need to care about `RACK_ENV`?
* It allowed me to choose a terrible password
* It did not work
![uploads/a9305df7-d897-4aca-a564-ce32e33f22e1/Screenshot 2016-04-13 10.46.15.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa9305df7-d897-4aca-a564-ce32e33f22e1%2FScreenshot+2016-04-13+10.46.15.png)

**Comment by pezholio** [comment]
* Yeah, the certificate is a thing we need to tackle in #71 I just put `#` there for now
* Heroku put all the env variables there, regardless of whether we need to customise them or not, which we could make easier by addressing #82 
* Yeah, that's another thing we can tackle with #82 
* Weird :/ Googling that seems like an intermittent Heroku problem - try again maybes?

**Comment by pikesley** [comment]
Is this because it has no data? 
![uploads/e5fedb69-ddce-408b-8b75-f5184447d7df/Screenshot 2016-04-13 10.59.13.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe5fedb69-ddce-408b-8b75-f5184447d7df%2FScreenshot+2016-04-13+10.59.13.png)

**Comment by pezholio** [comment]
Ah, it could well be. Try adding some, and see what happens. This is definitely A bug.

**Comment by pikesley** [comment]
Same difference 
![uploads/fdfbc290-4de8-4a19-9bd4-04c67733a6c6/Screenshot 2016-04-13 11.12.35.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffdfbc290-4de8-4a19-9bd4-04c67733a6c6%2FScreenshot+2016-04-13+11.12.35.png)

**Comment by pezholio** [comment]
Same error in the logs?

**Comment by pikesley** [comment]
Well it's just giving 503s

**Comment by pezholio** [comment]
What did you put in the `RACK_ENV`?

**Comment by pezholio** [comment]
Nope, that's a red herring. Not working for me either :rage4:

**Comment by pezholio** [comment]
This WORKED yesterday

**Comment by pikesley** [comment]
Hah

**Comment by pezholio** [comment]
Try changing `MONGOLAB_URI` to `MONGODB_URI` in your settings. Looks like Mongolab have changed the default env var name

**Comment by pezholio** [comment]
And now, it works! https://my-metrics-api.herokuapp.com/metrics

We need to change the mongoid.yml to accept `ENV['MONGODB_URI']` or `ENV['MONGOLAB_URI']`

**Comment by pikesley** [comment]
Oh FFS now I get a 404 when trying to POST

```
➔ curl -X POST -H 'Content-type: application/json' -d '{ "time": "2016-04-12T10:00:00", "value": 500 }' https://bothans:died@bothans-died.herokuapp.com/metrics
<h1>Not Found</h1>
```

```
2016-04-13T11:00:20.010082+00:00 heroku[router]: at=info method=POST path="/metrics" host=bothans-died.herokuapp.com request_id=23511b15-8393-4060-be56-acca81900b5a fwd="62.254.247.131" dyno=web.1 connect=1ms service=2ms status=404 bytes=241
```

**Comment by pezholio** [comment]
You need to post to /metrics/metric-name, not just to /metrics

**Comment by pikesley** [comment]
Ooh yeah
