### ISSUE TITLE
Design magic

### ISSUE THREAD

**Issue by Floppy** [theodi/bothan#73]

**Comment by Floppy** [comment]
@pezholio could we reuse the template you used for comma chameleon?

**Comment by Floppy** [comment]
And, in the template, check:

* [ ] Font (Helvetica Neue)
* [ ] Colours (make sure colours are from the brand)
* [ ] ODI logo in footer

**Comment by pikesley** [comment]
This layout is problematic: 

* the buttons at the top are designed to be two-abreast only and with 4 it gets very screwy on mobile
* the buttons really don't work with Helvetica
* the rendering of `pre` elements is rubbish

It might be fixable but I think I'm down a needless rabbit-hole now
