### ISSUE TITLE
Add demo of dashboard embedding to bothan.io

### ISSUE THREAD

**Issue by Floppy** [theodi/bothan#91]

**Comment by Floppy** [comment]
@pezholio just realised I archive an old ticket on this. Did I miss something?

**Comment by pezholio** [comment]
No, we still haven't done this. Relies on us fixing #92

**Comment by Floppy** [comment]
@pikesley do you reckon you could have a quick crack at this first thing this morning, so I can show it in my demo which is sometime after 10.30?

/me has become one of *those* people
